jobs:
  build:
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run test
      - store_test_results:
          path: reports
  publish:
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - run:
          name: Create npmrc file to authenticate with npm registry.
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-test-and-deploy:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - confirm-publish-if-tagged:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          type: approval
          requires:
            - build
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - confirm-publish-if-tagged
          
  
orbs:
  node: circleci/node@1.1
version: 2.1
