jobs:
  build:
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run test
      - store_test_results:
          path: reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

orbs:
  node: circleci/node@1.1
version: 2.1

